### ISSUE TITLE
Module not found: Can't resolve 'dns'

### ISSUE THREAD

**Issue by afzalsayed96** [jchiatt/nextjs-basic-auth#1]
Hi, I tried using this in next v10 and but it seems to return the following error:

```
event - build page: /
wait  - compiling...
error - ./node_modules/cacheable-lookup/source/index.js:10:1
Module not found: Can't resolve 'dns'
null
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
```

**Comment by jchiatt** [comment]
Hey @afzalsayed96 - mind posting some examples of how you're using the package?

**Comment by afzalsayed96** [comment]
Sorry, this has to do something with one of my own dependencies. Your package seems to work well without it.

Btw, great work! I had the same idea once for implementing basic auth but wasn't able to get it to work at first try.

Will be closing this. Cheers!
