### ISSUE TITLE
If you cancel, the page loads normally.

### ISSUE THREAD

**Issue by dougg0k** [jchiatt/nextjs-basic-auth#4]
the title.

**Comment by dougg0k** [comment]
Seems like it's because the build failed https://github.com/jchiatt/nextjs-basic-auth/commit/ba58912e1ffd88b8a939fd0f493a793e6a1b3d08 and changes were not published.

**Comment by nathan-k** [comment]
I was able to work around this issue with the following code:

```
export async function getServerSideProps(ctx) {
  const {req, res} = ctx;

  await httpAuthCheck(req, res);

  if (!req.headers.authorization) {
    res.end('<html>Unauthorized</html>')
  }

  return {
    props: {}
  }
}
```

**Comment by zmarty** [comment]
What on earth folks :) The most basic security feature of this library does not work.

**Comment by zmarty** [comment]
Here is a TypeScript workaround:

```javascript
export async function basicAuthCheck(req: IncomingMessage, res: ServerResponse): Promise<void> {
  await initializeBasicAuth({
    users: users,
  })(req, res);

  // Workaround for major bug: If you cancel, the page loads normally. - https://github.com/jchiatt/nextjs-basic-auth/issues/4
  if (res.statusCode == 401) {
    res.end('<html>Unauthorized</html>');
  }
}
```

**Comment by jchiatt** [comment]
Hi all, so sorry - this fix has been merged for months but my dumbass forgot to publish it!! 😅 

https://www.npmjs.com/package/nextjs-basic-auth

Version 0.1.3 just released - should work now. Cheers 🍻
